### ISSUE TITLE
Doesn't work with 2.4 

### ISSUE THREAD

**Issue by Gunnar-GO** [Team-Resurgent/CerbiosTool#4]
against the .nfo statement the actual version (at the moment 1.2.3 even 1.2.2) doesn't work with the BIOS 2.4.0B.

**Comment by jamesah2008** [comment]
`System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\james\AppData\Local\Temp\zayxfnhb.2sn'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at CerbiosTool.BiosUtility.LoadBiosComfig(String path, Config& config, Byte[]& biosData)
   at CerbiosTool.ApplicationUI.RenderUI()
   at CerbiosTool.Window.OnRenderFrame(FrameEventArgs e)
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at CerbiosTool.ApplicationUI.Run()
   at Program.<Main>$(String[] `args)``

**Comment by HoRnEyDvL** [comment]
Latest Build should work with Cerbios v2.4.2
